# title of website
title: 社内ナビゲーションページ

# description of website
description: datiewang's navigation site

# favicon of website
favicon: "https://github.com/datiewang.png?size=40"

# your website url
url: https://datiewang.github.io/arsnavi/

# github profile url
github: "https://github.com/datiewang"

# footer message
footer: © 2021-2021 @datiewang

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: google
    # 可选的搜索引擎
    engines:
      - google

content:
  categories:
    - name: 公式サイト
      sites:
        - name: エーアールシステム
          description: 公式サイト
          url: https://www.ar-system.co.jp/ 
        - name: サポートサイト
          description: サポート
          url: https://www.ar-system.co.jp/support/ 
    - name: Tools
      sites:
        - name: rakumo
          description: カレンダー
          url: https://a-rakumo.appspot.com/calendar#/calendars/group/all@ar-system.co.jp
        - name: ArsMember共有
          description: Google Drive
          url: https://drive.google.com/drive/folders/1JLFUU_ToXU6sLefX_pRYByu516r8D_cW
        - name: Qast
          description: Qast
          url: https://ars.qast.jp/
        - name: Wrike
          description: Wrike
          url: https://www.wrike.com/
        - name: 社内Wiki
          description: Wiki
          url: https://www.ar-system.co.jp/wiki/ 
        - name: 会議室のZoomのリンク
          description: 自由に使ってください
          url: https://docs.google.com/document/d/1fgYFWjhONOqPsx8B--JJ7QJTWI3YUzh-5n0KMDgsWa0/edit
        - name: WiFi
          description: 社内WiFiのパスワード
          url: https://www.ar-system.co.jp/wiki/doku.php?id=wifi          
    - name: 日報系
      sites:
        - name: 部署：定例議事録
          description: ◯△×□(?）
          url: https://docs.google.com/spreadsheets/u/2/d/1Yd7XrEvuhXRv1F6MM3xgT6XxvUHjBLgvNHkyutMwGaI/edit#gid=0
        - name: お客様対応管理シート
          description: 営業推進部用
          url: https://docs.google.com/spreadsheets/d/12ariElbLaHpcs2m-g5lCzoKkU-wjlAy8wmHsxI52h9M/edit?usp=sharing
        - name: 開発部日報
          description: 2022最新バージョン
          url: https://drive.google.com/drive/folders/1BsTLzPPtdtmv59mut9FvWhOtqzih1NO6   
    - name: インフラ
      sites:
        - name: OCI
          description: 管理画面
          url: https://cloud.oracle.com/  
        - name: OCI SR
          description: OCIのサポートサイト
          url: https://support.oracle.com/
        - name: Oracle再起動
          description: 通知のまとめ
          url: https://docs.google.com/spreadsheets/d/1l1gdPyBfm2vzluRukBUHBiwML0kBMAXu/edit#gid=219466182
        - name: OCI残金
          description: 日次コストと見積もり計算
          url: https://docs.google.com/spreadsheets/d/1ao2epZcpu0oovknDCYYxDCbl_uC1nby-/edit?rtpof=true  
    - name: マーケティング
      sites:
        - name: 定期MTG
          description: 毎朝10:15-10:30
          url: https://us06web.zoom.us/j/89739195105?pwd=MTVNRWxNZjZyNk1LSWZGKzdsN3JTQT09
        - name: 共有シート
          description: 「ARS_マーケティング強化PJ」
          url: https://docs.google.com/spreadsheets/d/1tEOdwOIs9M1KhDSmZTAsk7kAxqikLBXNYIl9Mf8AdQM/edit#gid=1709612637
     
     
