# title of website
title: arsnavi

# description of website
description: datiewang's navigation site

# favicon of website
favicon: "https://github.com/datiewang.png?size=40"

# your website url
url: https://datiewang.github.io/arsnavi/

# github profile url
github: "https://github.com/datiewang"

# footer message
footer: © 2021-2021 @datiewang

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: google
    # 可选的搜索引擎
    engines:
      - google

content:
  categories:
    - name: 公式サイト
      sites:
        - name: エーアールシステム
          description: 公式サイト
          url: https://www.ar-system.co.jp/ 
        - name: サポートサイト
          description: サポート
          url: https://www.ar-system.co.jp/support/
        - name: 社内Wiki
          description: Wiki
          url: https://www.ar-system.co.jp/wiki/        

